spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "here your clientId"
            clientSecret: "here your clientSecret"
            scope:
              - email
              - profile