spring:
  data:
    mongodb:
      auto-index-creation: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: "293073818976-1mrodnn44bb8n13uamtdlqdo8vm1rkr6.apps.googleusercontent.com"
            clientSecret: "A1j-HVt01feXb2M97kChXdZY"
            scope:
              - email
              - profile